language: python
install:
- pip install tox
script:
- tox -- --hypothesis-profile=ci --durations=20
jobs:
  include:
  - stage: test
    python: '3.8'
    env: TOXENV="lint"
  - python: '3.7'
    env: TOXENV="py37"
  - python: '3.8'
    env: TOXENV="py38"
  - stage: deploy
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: mark_bell
      password:
        secure: "EtJY3PaS1l+1K0hHFA7MHHOZGodi/QXU3+IquksAj+TBWOH0Q8dq/OKUNyBamuGkolJEwhvt5h+v6+ff+j3TAWTC4hgb/TJhx1CpIsxV07MKRVytgKAiIGBnFkdpeFU0WptdqRxiTyrLwBK2NS5c5IXqAACHPa783nmZ5T8I/yQwLsQnaV4AwOGrHPb7Wmmd7JEj2AVEXC3bM+d32hSjBEYksq05qhdAkH6Jl+m6L8rD+O4raWcCHMZ5ytEJC0Wtaee4+0ESYwyvw8AcUtV7paL92/tuEIsKouBOhs+mZ1arg5GTGYQk5YCyQ8E5bIFCWM/UiYCRF/9f64m+TJycD89CBi3LzTNaDoX+PK5amBo/pwrlWMa5imtJ+VC6g7cp0zfJk2QKzcHQROn86TS+g3P/2adDqyaq6WiJv6V5I0MYn87ddiBytGgNikRxVDaFGlwgdefy3aI5RvkGRlA9roXXkeX0KksV/O4vz8oSDFFLDF1O6SjvwGdGsOS6VR2CTP2SpwZ7z/l0t1OFrWC9XxAj/992UTKTWCK/8XbtrbDyMF5mPz7/KoW/39KNYbd1uDISIbCuaHY9OxJFUQb1gNqs8xHAti9zHG/EjvtcqTVrr8cjtcf/CwPdzh69H48OnVal7fBrK7GnmQjXzRK98cZ+uO2+L23+3ZFJM5B9MH8="
      on:
        tags: true

